/**
 * Code Generator Test Program
 * 
 * Tests the complete compilation pipeline: Source → Bytecode → Execution
 */

#include "../src/compiler/compiler.h"
#include "../src/vm/vm.h"
#include <iostream>

void testCompileAndRun(const std::string& source, const std::string& description) {
    std::cout << "\n=== " << description << " ===" << std::endl;
    std::cout << "Source code:" << std::endl;
    std::cout << source << std::endl;
    std::cout << std::endl;
    
    // Compile
    Compiler compiler;
    std::vector<std::string> bytecode = compiler.compile(source);
    
    if (compiler.hadError()) {
        std::cout << "Compilation Errors:" << std::endl;
        for (const auto& error : compiler.getErrors()) {
            std::cout << "  " << error << std::endl;
        }
        return;
    }
    
    // Print bytecode
    std::cout << "Generated Bytecode:" << std::endl;
    for (size_t i = 0; i < bytecode.size(); i++) {
        std::cout << "  [" << i << "] " << bytecode[i] << std::endl;
    }
    std::cout << std::endl;
    
    // Execute
    std::cout << "Execution:" << std::endl;
    std::cout << "----------------------------------------" << std::endl;
    VM vm;
    vm.run(bytecode);
    std::cout << "----------------------------------------" << std::endl;
}

int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "   CINEBREW Code Generator Test" << std::endl;
    std::cout << "========================================" << std::endl;
    
    // Test 1: Simple variable
    testCompileAndRun(
        "TAKE x = 5;\n"
        "POUR x;",
        "Test 1: Simple Variable"
    );
    
    // Test 2: Arithmetic
    testCompileAndRun(
        "TAKE a = 3;\n"
        "TAKE b = 5;\n"
        "TAKE sum = a + b;\n"
        "POUR sum;",
        "Test 2: Arithmetic Expression"
    );
    
    // Test 3: Conditional
    testCompileAndRun(
        "TAKE x = 10;\n"
        "IF x > 5 {\n"
        "    POUR x;\n"
        "}",
        "Test 3: Conditional"
    );
    
    // Test 4: Loop
    testCompileAndRun(
        "TAKE i = 1;\n"
        "LOOP i <= 5 {\n"
        "    POUR i;\n"
        "    i = i + 1;\n"
        "}",
        "Test 4: Loop"
    );
    
    // Test 5: Function
    testCompileAndRun(
        "SCENE add(a, b) {\n"
        "    SHOT a + b;\n"
        "}\n"
        "TAKE result = add(3, 5);\n"
        "POUR result;",
        "Test 5: Function Call"
    );
    
    // Test 6: Complex expression
    testCompileAndRun(
        "TAKE result = (3 + 5) * 2;\n"
        "POUR result;",
        "Test 6: Complex Expression"
    );
    
    // Test 7: Comparison
    testCompileAndRun(
        "TAKE a = 10;\n"
        "TAKE b = 5;\n"
        "TAKE gt = a > b;\n"
        "POUR gt;\n"
        "TAKE eq = a == 10;\n"
        "POUR eq;",
        "Test 7: Comparisons"
    );
    
    std::cout << "\n========================================" << std::endl;
    std::cout << "All tests completed!" << std::endl;
    std::cout << "========================================" << std::endl;
    
    return 0;
}

