/**
 * CINEBREW Code Generator
 * 
 * ============================================================================
 * WHAT IS CODE GENERATION?
 * ============================================================================
 * 
 * Code generation is the process of translating the Abstract Syntax Tree
 * (AST) into bytecode instructions that the VM can execute.
 * 
 * The Pipeline:
 *   Source Code → Lexer → Parser → Semantic Analyzer → Code Generator → Bytecode
 * 
 * HOW IT WORKS
 * 
 * The code generator walks the AST and generates bytecode instructions:
 *   - Expression nodes → Stack operations
 *   - Statement nodes → Control flow instructions
 *   - Function nodes → Function definition bytecode
 * 
 * ============================================================================
 */

#ifndef CODEGEN_H
#define CODEGEN_H

#include "ast.h"
#include "semantic.h"
#include <vector>
#include <string>
#include <memory>
#include <unordered_map>

/**
 * Code Generator
 * 
 * Translates AST into bytecode instructions.
 */
class CodeGenerator {
public:
    CodeGenerator();
    
    // Main function: generate bytecode from AST
    std::vector<std::string> generate(std::unique_ptr<Program>& program);
    
    // Get generated bytecode
    std::vector<std::string> getBytecode() const { return bytecode_; }
    
    // Check if there were any errors
    bool hadError() const { return hadError_; }
    
    // Get error message
    std::string getError() const { return errorMessage_; }

private:
    // ========================================================================
    // STATE
    // ========================================================================
    std::vector<std::string> bytecode_;
    std::unordered_map<std::string, int> labelCounter_;  // For unique labels
    bool hadError_;
    std::string errorMessage_;
    
    // ========================================================================
    // BYTECODE GENERATION
    // ========================================================================
    void emit(const std::string& instruction);
    std::string newLabel(const std::string& prefix);
    
    // ========================================================================
    // ERROR HANDLING
    // ========================================================================
    void error(const std::string& message);
    
    // ========================================================================
    // AST WALKING
    // ========================================================================
    void visitProgram(Program* program);
    void visitStmt(Stmt* stmt);
    void visitExpr(Expr* expr);
    
    // Statements
    void visitDeclaration(DeclarationStmt* stmt);
    void visitAssignment(AssignmentStmt* stmt);
    void visitPrint(PrintStmt* stmt);
    void visitIf(IfStmt* stmt);
    void visitLoop(LoopStmt* stmt);
    void visitBreak(BreakStmt* stmt);
    void visitContinue(ContinueStmt* stmt);
    void visitReturn(ReturnStmt* stmt);
    void visitFunction(FunctionStmt* stmt);
    void visitBlock(BlockStmt* stmt);
    
    // Expressions
    void visitLiteral(LiteralExpr* expr);
    void visitVariable(VariableExpr* expr);
    void visitBinary(BinaryExpr* expr);
    void visitUnary(UnaryExpr* expr);
    void visitCall(CallExpr* expr);
};

#endif // CODEGEN_H

