/**
 * CINEBREW Compiler
 * 
 * Complete compiler that ties together all stages:
 * Lexer → Parser → Semantic Analyzer → Code Generator
 */

#ifndef COMPILER_H
#define COMPILER_H

#include "lexer.h"
#include "parser.h"
#include "semantic.h"
#include "codegen.h"
#include <string>
#include <vector>
#include <memory>

/**
 * Compiler Class
 * 
 * Main compiler interface that orchestrates all compilation stages.
 */
class Compiler {
public:
    Compiler();
    
    // Main function: compile source code to bytecode
    std::vector<std::string> compile(const std::string& source);
    
    // Check if compilation was successful
    bool hadError() const;
    
    // Get error messages
    std::vector<std::string> getErrors() const;
    
    // Get generated bytecode
    std::vector<std::string> getBytecode() const;

private:
    // Note: Lexer, Parser, SemanticAnalyzer, and CodeGenerator
    // are created on-demand in compile() method because they require
    // constructor arguments (source, tokens, etc.)
    
    std::vector<std::string> errors_;
    std::vector<std::string> bytecode_;
    bool hadError_;
};

#endif // COMPILER_H

